[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.81"
license = "AGPL-3.0"
homepage = "https://nullis.xyz/nexum"
repository = "https://github.com/nullisxyz/nexum"
exclude = [".github/"]

[package]
name = "nexum"
build = "build.rs"

[lib]
path = "src/lib.rs" # Dummy path for a lib target; could be any empty or placeholder file.

[workspace]
members = [
    "crates/primitives",
    "crates/primitives-traits",
    "crates/chrome-sys",
    "crates/worker",
    "crates/injected",
    "crates/injector",
    # "crates/tui"
]

# Explicitly set the resolver to version 2, which is the default for packages with edition >= 2021
# https://doc.rust-lang.org/edition-guide/rust-2021/default-cargo-resolver.html
resolver = "2"

[workspace.dependencies]
async-lock = "2.5"
derive_more = { version = "1.0.0", default-features = false, features = ["display"] }
wasm-bindgen = { version = "0.2.95", features = ["serde", "serde_json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
gloo-utils = "0.2.0"
js-sys = "0.3.72"
futures = "0.3"
web-sys = { version = "0.3.72", features = ["Window", "WebSocket", "console", "MessageEvent", "Event", "EventListener", "Element", "HtmlHeadElement", "HtmlScriptElement", "CustomEvent", "CustomEventInit"] }
serde-wasm-bindgen = "0.6.5"
wasm-bindgen-test = "0.3"
tracing = "0.1.40"
wasm-tracing = "0.2.1"
wasm-bindgen-futures = "0.4.45"
jsonrpsee = { version = "0.24.7", features = ["wasm-client", "jsonrpsee-core", "jsonrpsee-types", "client-core", "client-web-transport" ] }
url = "2.5.2"
uuid = { version = "1", features = ["v4", "js"] }
gloo-timers = { version = "0.3.0", features = ["futures"] }

chrome-sys = { path = "crates/chrome-sys" }
worker = { path = "crates/worker" }
injected = { path = "crates/injected" }
injector = { path = "crates/injector"}
nexum-primitives = { path = "crates/primitives" }
nexum-primitives-traits = { path = "crates/primitives-traits" }

console_error_panic_hook = "0.1.7"
