[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.83"
license = "AGPL-3.0"
homepage = "https://nxm.rs"
repository = "https://github.com/nxm-rs/nexum"
exclude = [".github/"]

[workspace]
members = [
    "crates/primitives/",
    "crates/extension/chrome-sys/",
    "crates/extension/worker/",
    "crates/extension/injected/",
    "crates/extension/injector/",
    "crates/extension/browser-ui/",
    "crates/tui/",
    "crates/rpc/",
]
default-members = ["crates/rpc", "crates/tui/"]

# Explicitly set the resolver to version 2, which is the default for packages with edition >= 2021
# https://doc.rust-lang.org/edition-guide/rust-2021/default-cargo-resolver.html
resolver = "2"

[workspace.dependencies]
async-lock = "2.5"
derive_more = { version = "1.0.0", default-features = false, features = ["display"] }
wasm-bindgen = { version = "0.2.95", features = ["serde", "serde_json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
gloo-utils = "0.2.0"
js-sys = "0.3.72"
futures = "0.3"
web-sys = { version = "0.3.72", features = ["Window", "WebSocket", "console", "MessageEvent", "Event", "EventListener", "Element", "HtmlHeadElement", "HtmlScriptElement", "CustomEvent", "CustomEventInit", "Storage"] }
serde-wasm-bindgen = "0.6.5"
wasm-bindgen-test = "0.3"
tracing = "0.1.40"
tracing-error = "0.2.0"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "serde"] }
wasm-tracing = "0.2.1"
wasm-bindgen-futures = "0.4.45"
jsonrpsee = { version = "0.24.7", features = ["wasm-client", "jsonrpsee-core", "jsonrpsee-types", "client-core", "client-web-transport" ] }
url = { version = "2.5.2", features = ["serde"] }
uuid = { version = "1", features = ["v4", "js"] }
gloo-timers = { version = "0.3.0", features = ["futures"] }
tokio = { version = "1.45.0", features = ["full"] }
clap = { version = "4.5.38", features = ["derive"] }
eyre = "0.6.12"

console_error_panic_hook = "0.1.7"

alloy-chains = { version = "0.1.47", features = ["serde"] }
alloy = { version = "1.0.3", features = ["signer-keystore", "provider-ws"] }

chrome-sys = { path = "crates/extension/chrome-sys" }
worker = { path = "crates/extension/worker" }
injected = { path = "crates/extension/injected" }
injector = { path = "crates/extension/injector"}
nexum-primitives = { path = "crates/primitives" }
rpc = { path = "crates/rpc" }
