[package]
name = "nexum-keycard"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
description = "Rust implementation for interacting with Keycards for secure key management"

[dependencies]
## nexum-apdu
nexum-apdu-core.workspace = true
nexum-apdu-globalplatform.workspace = true
nexum-apdu-macros.workspace = true
nexum-apdu-transport-pcsc.workspace = true

## crypto
alloy-primitives = { workspace = true, features = ["k256"] }
cbc = { workspace = true, features = ["block-padding"] }
coins-bip39 = { workspace = true, features = ["english"] }
pbkdf2.workspace = true
rand.workspace = true
rand_v8.workspace = true
sha2.workspace = true
alloy-signer.workspace = true
coins-bip32.workspace = true
aes.workspace = true
block-padding.workspace = true
cbc-mac.workspace = true
cipher.workspace = true
k256.workspace = true
zeroize = { workspace = true, optional = true }

## bytes and encoding
bytes.workspace = true
iso7816-tlv.workspace = true
base64.workspace = true
unicode-normalization.workspace = true
generic-array.workspace = true

## misc
thiserror = { workspace = true, optional = true }
anyhow.workspace = true
tracing.workspace = true
derive_more.workspace = true

[dev-dependencies]
rand_v8.workspace = true

[features]
default = ["std", "zeroize"]
std = ["thiserror", "nexum-apdu-core/std", "cipher/std", "cbc-mac/std"]
zeroize = ["dep:zeroize", "cipher/zeroize", "aes/zeroize"]
cli = ["dep:clap"]

[dependencies.clap]
workspace = true
optional = true
