# Configuration file for [`cargo-release`](https://github.com/crate-ci/cargo-release)
# See: https://github.com/crate-ci/cargo-release/blob/master/docs/reference.md

allow-branch = ["main"]
sign-commit = true
sign-tag = true
shared-version = true
publish = true  # Enable publishing to crates.io
pre-release-commit-message = "chore: release {{version}}"
tag-prefix = ""
tag-message = "Release {{version}}"
push = true  # Make sure we push the tag
pre-release-hook = [
    "bash",
    "-c",
    "$WORKSPACE_ROOT/scripts/changelog.sh --tag v{{version}}",
]
owners = ["github:nullisxyz:core"]
rate-limit.existing-packages = 50
