name: Build and Package Extension

# run this action on main branch and every pull request
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

common_steps: &common_steps
  - name: Checkout code
    uses: actions/checkout@v4

  - name: Install Rust
    uses: dtolnay/rust-toolchain@nightly
    with:
      target: wasm32-unknown-unknown

  - uses: actions/cache@v4
    with:
      path: |
        ~/.cargo/bin/
        ~/.cargo/registry/index/
        ~/.cargo/registry/cache/
        ~/.cargo/git/db/
        target/
      key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

  - name: Install cargo-binstall
    run: curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

  - name: Install wasm-pack
    run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

  - name: Install trunk and just
    run: cargo binstall trunk just

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - *common_steps
      - name: Cargo check
        run: just check

  fmt:
    runs-on: ubuntu-latest
    steps:
      - *common_steps
      - name: Cargo fmt
        run: cargo fmt --all --check

  build:
    runs-on: ubuntu-latest
    steps:
      - *common_steps
      - name: Cargo build
        run: just build

  build-and-package-extension:
    runs-on: ubuntu-latest
    steps:
      - *common_steps
      - name: Build extension
        run: just be
      - name: Upload Firefox artifact  
        uses: actions/upload-artifact@v4
        with:
          name: firefox-extension
          path: crates/nexum/extension/dist/
